### PR TITLE
Possibility to define cluster name to configuration

### PR DESCRIPTION
**Pull request by zetaab**

### CODE REVIEW

**Comment by Issif** [comment]
Hi,

Thanks for your PR, I reviewed it quickly, all seems OK.

Anyhow, you gave me an idea, specifying a list of key:values for adding anything we want as fields. What do you think about? It's only a generic pattern of you have done.

**Comment by zetaab** [comment]
@Issif the problem what I see is that its little bit difficult to support yaml file and ENV variables in that key:value thing. Okay it works if we just define like `ExtraLabels string`. Then it could be something like

```
		extraLabels := strings.Split(config.ExtraLabels, ",")
		for _, label := range extraLabels {
			splitted := strings.Split(label, ":")
			if len(splitted) == 2 {
				field.Title = splitted[0]
				field.Value = splitted[1]
				field.Short = true
				fields = append(fields, field)
			}
		}
```

This works with env variables quite nice, if you just define `export EXTRALABELS=foo:bar,heh:hah`. However, it looks little bit stupid in yaml file?

**Comment by Issif** [comment]
I agree it seems weird in YAML to list elements in a single line like with envvars. I need to check how `viper` package handles that cases, in classic YAML we can provide a list of `key:value` like that normally :

```yaml
parameters:
  firstKey: value1
  secondKey: value2
```

**Comment by Issif** [comment]
@zetaab

I did it in branch : https://github.com/Issif/falcosidekick/tree/custom_fields

We can now add any `key:value` we want via .yaml or envvars.

image

I updated the README in the dedicated branch, can you please test on your side?

**Comment by zetaab** [comment]
@Issif for me it looks what I want. And that will help others as well in many usecases. Feel free to push your way forward :)

**Comment by Issif** [comment]
@zetaab

Thanks for your idea and comment.

**Pull request closed without merging**
